apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: eksclusterwithvpc.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: EksclusterWithVpc
    spec:
      name: string
      region: string
      cidr:
        vpcCidr: string | default="10.0.0.0/16"
        publicSubnet1Cidr: string | default="10.0.1.0/24"
        publicSubnet2Cidr: string | default="10.0.2.0/24"
        privateSubnet1Cidr: string | default="10.0.11.0/24"
        privateSubnet2Cidr: string | default="10.0.12.0/24"
      accountId: string
      k8sVersion: string
      nodesCount: integer
  resources:
  - id: vpc
    template:
      apiVersion: kro.run/v1alpha1
      kind: Vpc
      metadata:
        name: ${schema.spec.name}
      spec:
        name: ${schema.spec.name}
        region: ${schema.spec.region}
        cidr:
          vpcCidr: ${schema.spec.cidr.vpcCidr}
          publicSubnet1Cidr: ${schema.spec.cidr.publicSubnet1Cidr}
          publicSubnet2Cidr: ${schema.spec.cidr.publicSubnet2Cidr}
          privateSubnet1Cidr: ${schema.spec.cidr.privateSubnet1Cidr}
          privateSubnet2Cidr: ${schema.spec.cidr.privateSubnet2Cidr}
  - id: eks
    template:
      apiVersion: kro.run/v1alpha1
      kind: EksCluster
      metadata:
        name: ${schema.spec.name}
      spec:
          name: ${schema.spec.name}
          region: ${schema.spec.region}
          subnets:
            controlplane:
              subnet1ID: ${vpc.status.privateSubnet1ID}
              subnet2ID: ${vpc.status.privateSubnet2ID}
            workers:
              subnet1ID: ${vpc.status.privateSubnet1ID}
              subnet2ID: ${vpc.status.privateSubnet2ID}
          accountId: ${schema.spec.accountId}
          k8sVersion: ${schema.spec.k8sVersion}
          nodesCount: ${schema.spec.nodesCount}
